import { Injectable } from "@angular/core";
import { Recipe } from "./recipes.model";
import { Ingredient } from "./ingredient.model";
import { Instructions } from "./instructions.model";
@Injectable()
export class RecipeService {
 
    private recipes: Recipe[] = [
        new Recipe(
            0,
            'Capsicum Corn Pizza',
            'https://api.pizzahut.io/v1/content/en-in/in-1/images/pizza/country-feast-cheese-maxx.01396975bebd766302f117884bbb9304.1.jpg',
            4.2,
            4,
            '15 min',
            '20 min',
            'pizza',
            [
                new Ingredient('2 readymade pizza base'),
                new Ingredient('1 medium onion ( finely chopped)'),
                new Ingredient('1 medium tomato (finely chopped)'),
                new Ingredient(' 2 tbs garlic ( finely chopped)'),
                new Ingredient(' 2 tbs butter'),
                new Ingredient(' 1 tsp chilli flakes'),
                new Ingredient('  1 tsp oregano seasoning'),
                new Ingredient(' 2 tbs tomato ketchup'),
                new Ingredient(' 2 tbs oil'),
                new Ingredient('1 capsicum ( cut into strips)'),
                new Ingredient(' 1/2 cup boiled sweet corn'),
                new Ingredient(' Mozarella or processed cheese')
            ],
            [
                new Instructions("In a pan heat oil and add garlic. Saute till it gives a nice aroma. Add the onions and saute till soft."),
                new Instructions("Add the tomatoes, chilli flakes, and oregano seasoning and cook till tomatoes are soft."),
                new Instructions("Cool and grind to a paste."),
                new Instructions("Add the tomato ketchup to this paste and mix well."),
                new Instructions("Take a pizza base and spread the sauce on the base."),
                new Instructions("Put the pizza toppings of corn and capsicum. Grate cheese on top."),
                new Instructions("Heat a flat bottomed pan or tava and put 1 tbs of butter. When butter melts place the prepared pizza on it and cover with a lid."),
                new Instructions("Heat on slow flame till cheese melts and base turns a little crisp.")
            ]),
          new Recipe(
              1,
            'Paneer Pizza',
            'https://product-assets.faasos.io/production/product/image_es_1608634656049_Picante%20Paneer%20Cheese%20Burst%20Pizza.jpg',
            4.5,
            4,
            '20 min',
            '30 min',
            'pizza',
            [
                new Ingredient('2 readymade pizza base'),
                new Ingredient( '100 gm paneer'),
                new Ingredient('1 medium tomato (finely chopped)'),
                new Ingredient(' 2 tbs garlic ( finely chopped)'),
                new Ingredient(' 2 tbs butter'),
                new Ingredient(' 1 tsp chilli flakes'),
                new Ingredient('  1 tsp oregano seasoning'),
                new Ingredient(' 2 tbs tomato ketchup'),
                new Ingredient(' 2 tbs oil'),
                new Ingredient('1 capsicum ( cut into strips)'),
                new Ingredient(' 1/2 cup boiled sweet corn'),
                new Ingredient(' Mozarella or processed cheese')
            ],
            [
                new Instructions("In a pan heat oil and add garlic. Saute till it gives a nice aroma. Add the onions and saute till soft."),
                new Instructions("Add the tomatoes, chilli flakes, and oregano seasoning and cook till tomatoes are soft."),
                new Instructions("Cool and grind to a paste."),
                new Instructions("Add the tomato ketchup to this paste and mix well."),
                new Instructions("Take a pizza base and spread the sauce on the base."),
                new Instructions("Put the pizza toppings of corn and capsicum. Grate cheese on top."),
                new Instructions("Heat a flat bottomed pan or tava and put 1 tbs of butter. When butter melts place the prepared pizza on it and cover with a lid."),
                new Instructions("Heat on slow flame till cheese melts and base turns a little crisp.")
              ]),
      new Recipe(
            2,
            'Margherita  Pizza',
            'https://previews.123rf.com/images/mizina/mizina1704/mizina170400133/76090138-people-hand-taking-slice-of-pizza-margherita-pizza-margarita-and-child-hand-close-up.jpg',
            4.1,
            4,
            '15 min',
            '20 min',
            'pizza',
            [
                new Ingredient('2 readymade pizza base'),
                new Ingredient( 'Margherita cheese'),
                new Ingredient('1 medium tomato (finely chopped)'),
                new Ingredient(' 2 tbs garlic ( finely chopped)'),
                new Ingredient(' 2 tbs butter'),
                new Ingredient(' 1 tsp chilli flakes'),
                new Ingredient('  1 tsp oregano seasoning'),
                new Ingredient(' 2 tbs tomato ketchup'),
                new Ingredient(' 2 tbs oil'),
                new Ingredient('1 capsicum ( cut into strips)'),
                new Ingredient(' 1/2 cup boiled sweet corn'),
                new Ingredient(' Mozarella or processed cheese')
            ],
            [
                new Instructions("In a pan heat oil and add garlic. Saute till it gives a nice aroma. Add the onions and saute till soft."),
                new Instructions("Add the tomatoes, chilli flakes, and oregano seasoning and cook till tomatoes are soft."),
                new Instructions("Cool and grind to a paste."),
                new Instructions("Add the tomato ketchup to this paste and mix well."),
                new Instructions("Take a pizza base and spread the sauce on the base."),
                new Instructions("Put the pizza toppings of corn and capsicum. Grate cheese on top."),
                new Instructions("Heat a flat bottomed pan or tava and put 1 tbs of butter. When butter melts place the prepared pizza on it and cover with a lid."),
                new Instructions("Heat on slow flame till cheese melts and base turns a little crisp.")
            ]),
        new Recipe(
             3,
            'Cheese  Pizza',
            'https://img.freepik.com/premium-photo/slice-hot-italian-pizza-with-stretching-cheese-pizza-four-cheeses-with-basil_79782-3174.jpg',
            3.9,
            4,
            '15 min',
            '20 min',
            'pizza',
            [
                new Ingredient('2 readymade pizza base'),
                new Ingredient( 'Mozarella cheese'),
                new Ingredient('1 medium tomato (finely chopped)'),
                new Ingredient(' 2 tbs garlic ( finely chopped)'),
                new Ingredient(' 2 tbs butter'),
                new Ingredient(' 1 tsp chilli flakes'),
                new Ingredient('  1 tsp oregano seasoning'),
                new Ingredient(' 2 tbs tomato ketchup'),
                new Ingredient(' 2 tbs oil'),
                new Ingredient('1 capsicum ( cut into strips)'),
                new Ingredient(' 1/2 cup boiled sweet corn'),
                new Ingredient(' Mozarella or processed cheese')
            ],
            [
                new Instructions("In a pan heat oil and add garlic. Saute till it gives a nice aroma. Add the onions and saute till soft."),
                new Instructions("Add the tomatoes, chilli flakes, and oregano seasoning and cook till tomatoes are soft."),
                new Instructions("Cool and grind to a paste."),
                new Instructions("Add the tomato ketchup to this paste and mix well."),
                new Instructions("Take a pizza base and spread the sauce on the base."),
                new Instructions("Put the pizza toppings of corn and capsicum. Grate cheese on top."),
                new Instructions("Heat a flat bottomed pan or tava and put 1 tbs of butter. When butter melts place the prepared pizza on it and cover with a lid."),
                new Instructions("Heat on slow flame till cheese melts and base turns a little crisp.")
            ]),
         new Recipe(
        4,
            'Veggie  Pizza',
            'https://cookingteach.com/media/posts/10/Veggie-Pizza-cooking-teach.jpg',
            3.9,
            4,
            '15 min',
            '20 min',
            'pizza',
            [
                new Ingredient('2 readymade pizza base'),
                new Ingredient( 'Mozarella cheese'),
                new Ingredient('1 medium tomato (finely chopped)'),
                new Ingredient(' 2 tbs garlic ( finely chopped)'),
                new Ingredient(' 2 tbs butter'),
                new Ingredient(' 1 tsp chilli flakes'),
                new Ingredient('  1 tsp oregano seasoning'),
                new Ingredient(' 2 tbs tomato ketchup'),
                new Ingredient(' 2 tbs oil'),
                new Ingredient('1 capsicum ( cut into strips)'),
                new Ingredient(' 1/2 cup boiled sweet corn'),
                new Ingredient(' Mozarella or processed cheese')
            ],
            [
                new Instructions("In a pan heat oil and add garlic. Saute till it gives a nice aroma. Add the onions and saute till soft."),
                new Instructions("Add the tomatoes, chilli flakes, and oregano seasoning and cook till tomatoes are soft."),
                new Instructions("Cool and grind to a paste."),
                new Instructions("Add the tomato ketchup to this paste and mix well."),
                new Instructions("Take a pizza base and spread the sauce on the base."),
                new Instructions("Put the pizza toppings of corn and capsicum. Grate cheese on top."),
                new Instructions("Heat a flat bottomed pan or tava and put 1 tbs of butter. When butter melts place the prepared pizza on it and cover with a lid."),
                new Instructions("Heat on slow flame till cheese melts and base turns a little crisp.")
             ]),
              new Recipe(
        5,
            'Rajma Patty Burger',
            'https://i1.wp.com/wp-backend.thefearlesscooking.com/wp-content/uploads/2021/04/DSC01126-01.jpeg',
            5.1,
            2,
            '10 min',
            '20 min',
            'Burger',
            [
                new Ingredient(' 1 Bread bun'),
                new Ingredient( '  1 boiled potato'),
                new Ingredient(' 1 / 2 boiled rajma'),
                new Ingredient( ' 1 / 2 peas'),
                new Ingredient( '   1 / 2 red chilli powder'),
                new Ingredient( '  1 / 2 tsp Piri Piri powder'),
                new Ingredient('   1 / 2 tsp pepper'),
                new Ingredient(   '  Salt as per taste'),
                new Ingredient(' 2 tbs oil'),
                new Ingredient( '  1 onion and tomato, sliced'),
                new Ingredient( ' 5 corn flour slurry'),
                new Ingredient( ' Breadcrumbs')
            ],
            [
                new Instructions(  'Take the boiled rajma, potatoes, peas and small bread pieces. Combine this with masalas and mix.'),
                new Instructions( 'Give it the shape of Tikki and dip the Tikki in cornflour slurry and bread crumbs. Pan fry this till golden brown.'),
                new Instructions('Then take the buns and lightly toast them with butter on a pan. Take it out and assemble your burger'),
                new Instructions( 'Now first, add a layer of tomato ketchup on one side of the burger, then place the patty, cheese, sliced onion and tomato.'),
                new Instructions('From the top, add sauces like mustard sauce, mayonnaise, or any other sauce of your choice.'),
                new Instructions(    'Finally, close the bun, serve it with fries and enjoy!.'),
              
                  ]),
                  new Recipe(
        6,
            'Potato Burger',
           'https://www.cooking4allseasons.com/wp-content/uploads/2014/10/PotatoandSweetCornSliders.jpg',
            5.1,
            2,
            '15 min',
            '35 min',
            'Burger',
            [
                new Ingredient(' 4 Tbsp Olive oil'),
                new Ingredient( ' 1 / 2 Leek' ),
                new Ingredient('  1 / 3 cup Celery, chopped'),
                new Ingredient('  1 / 2 Onion, chopped'),
                new Ingredient('  1 cup Corn kernels(frozen)'),
                new Ingredient(' Few sprigs Thyme'),
                new Ingredient('  Few Coriander leaves'),
                new Ingredient(' 2 large Potatoes(peeled)'),
                new Ingredient(   ' 1 tsp Garlic chives, chopped'),
                new Ingredient( ' 1 Lettuce leaf'),
                new Ingredient(  ' 4 - 5 tbsp Oil(for frying)'),
                new Ingredient( '3- 4 Tomatoes')
            ],
            [
                new Instructions("In a pan heat oil and add garlic. Saute till it gives a nice aroma. Add the onions and saute till soft."),
                new Instructions("Add the tomatoes, chilli flakes, and oregano seasoning and cook till tomatoes are soft."),
                new Instructions('Peel the cooked potatoes, grate or mash the potatoes in a bowl.'),
                new Instructions('Mix the potatoes with the corn, onion, leeks, celery.'),
                new Instructions('Add the jalapenos, a large handful of coriander and crumble the feta cheese into the mixture.'),
                new Instructions(  'Mix all the ingredients really well and season to taste.'),
                new Instructions( 'Put the bread crumbs in a plate,Shape the burger patties into with a cutter or mould.'),
                new Instructions('Dip the patty in the batter and cover with breadcrumbs,Heat up 2 tbsp oil in pan and shallow fry until nice and brown.'),
                new Instructions( 'Slice up some tomatoes and put it in a lettuce leaf for the garnish along with some gherkins.'),
                new Instructions( 'Heat the buns in the oven.'),
                new Instructions( 'Put the lettuce, tomatoes and gherkins inside the bun along with the patty and serve with chips on the side.')
                      ]),
                    new Recipe(
        7,
            'Paneer & Green Peas Burger',
           'https://img.freepik.com/premium-photo/homemade-vegan-burgers-with-chickpea-pattie-green-peas-beetroot-hummus_128659-346.jpg',
            5.5,
            2,
            '15 min',
            '25 min',
            'Burger',
            [
                new Ingredient( ' 1 Bread bun'),
                new Ingredient(   '  1 cup paneer' ),
                new Ingredient('  1 / 3 cup Celery, chopped'),
                new Ingredient('  1 / 2 Onion, chopped'),
                new Ingredient(' 1 / 2 peas'),
                new Ingredient(' Few sprigs Thyme'),
                new Ingredient('  Few Coriander leaves'),
                new Ingredient(  ' Breadcrumbs'),
                new Ingredient(   ' 1 tsp Garlic chives, chopped'),
                new Ingredient( ' 1 Lettuce leaf'),
                new Ingredient(  ' 4 - 5 tbsp Oil(for frying)'),
                new Ingredient( '3- 4 Tomatoes')
            ],
            [
                new Instructions( 'Take the boiled rajma, potatoes, peas and small bread pieces. Combine this with masalas and mix.'),
                new Instructions("Add the tomatoes, chilli flakes, and oregano seasoning and cook till tomatoes are soft."),
                new Instructions(  'Give it the shape of Tikki and dip the Tikki in cornflour slurry and bread crumbs. Pan fry this till golden brown.'),
                new Instructions('Mix the potatoes with the corn, onion, leeks, celery.'),
                new Instructions('Add the jalapenos, a large handful of coriander and crumble the feta cheese into the mixture.'),
                new Instructions(  'Mix all the ingredients really well and season to taste.'),
                new Instructions( 'Put the bread crumbs in a plate,Shape the burger patties into with a cutter or mould.'),
                new Instructions('Dip the patty in the batter and cover with breadcrumbs,Heat up 2 tbsp oil in pan and shallow fry until nice and brown.'),
                new Instructions( 'Slice up some tomatoes and put it in a lettuce leaf for the garnish along with some gherkins.'),
                new Instructions( 'Heat the buns in the oven.'),
                new Instructions( 'Put the lettuce, tomatoes and gherkins inside the bun along with the patty and serve with chips on the side.')
                        ]),
             new Recipe(
        8,
           'Vegie Burger',
           'https://st2.depositphotos.com/1290614/6909/i/450/depositphotos_69091113-stock-photo-quinoa-burger-with-avocado.jpg',
            5.5,
            2,
            '15 min',
            '25 min',
            'Burger',
            [
                new Ingredient( ' 1 Bread bun'),
                new Ingredient(   '  1 cup paneer' ),
                new Ingredient('  1 / 3 cup Celery, chopped'),
                new Ingredient('  1 / 2 Onion, chopped'),
                new Ingredient(' 1 / 2 peas'),
                new Ingredient(' Few sprigs Thyme'),
                new Ingredient('  Few Coriander leaves'),
                new Ingredient(  ' Breadcrumbs'),
                new Ingredient(   ' 1 tsp Garlic chives, chopped'),
                new Ingredient( ' 1 Lettuce leaf'),
                new Ingredient(  ' 4 - 5 tbsp Oil(for frying)'),
                new Ingredient( '3- 4 Tomatoes')
            ],
            [
                new Instructions( 'Take the boiled rajma, potatoes, peas and small bread pieces. Combine this with masalas and mix.'),
                new Instructions("Add the tomatoes, chilli flakes, and oregano seasoning and cook till tomatoes are soft."),
                new Instructions(  'Give it the shape of Tikki and dip the Tikki in cornflour slurry and bread crumbs. Pan fry this till golden brown.'),
                new Instructions('Mix the potatoes with the corn, onion, leeks, celery.'),
                new Instructions('Add the jalapenos, a large handful of coriander and crumble the feta cheese into the mixture.'),
                new Instructions(  'Mix all the ingredients really well and season to taste.'),
                new Instructions( 'Put the bread crumbs in a plate,Shape the burger patties into with a cutter or mould.'),
                new Instructions('Dip the patty in the batter and cover with breadcrumbs,Heat up 2 tbsp oil in pan and shallow fry until nice and brown.'),
                new Instructions( 'Slice up some tomatoes and put it in a lettuce leaf for the garnish along with some gherkins.'),
                new Instructions( 'Heat the buns in the oven.'),
                new Instructions( 'Put the lettuce, tomatoes and gherkins inside the bun along with the patty and serve with chips on the side.')
                        ]),
               new Recipe(
            9,
           'Lamb & Tomato Burger',
          'https://i.pinimg.com/originals/c0/ba/34/c0ba34dc7e051cc9411093744dfa7327.jpg',
            5.5,
            3,
            '15 min',
            '25 min',
            'Burger',
            [
                new Ingredient( ' 1 Bread bun'),
                new Ingredient(   '  1 cup paneer' ),
                new Ingredient('  1 / 3 cup Celery, chopped'),
                new Ingredient('  1 / 2 Onion, chopped'),
                new Ingredient(' 1 / 2 peas'),
                new Ingredient(' Few sprigs Thyme'),
                new Ingredient('  Few Coriander leaves'),
                new Ingredient(  ' Breadcrumbs'),
                new Ingredient(   ' 1 tsp Garlic chives, chopped'),
                new Ingredient( ' 1 Lettuce leaf'),
                new Ingredient(  ' 4 - 5 tbsp Oil(for frying)'),
                new Ingredient( '3- 4 Tomatoes')
            ],
            [
                new Instructions( 'Take the boiled rajma, potatoes, peas and small bread pieces. Combine this with masalas and mix.'),
                new Instructions("Add the tomatoes, chilli flakes, and oregano seasoning and cook till tomatoes are soft."),
                new Instructions(  'Give it the shape of Tikki and dip the Tikki in cornflour slurry and bread crumbs. Pan fry this till golden brown.'),
                new Instructions('Mix the potatoes with the corn, onion, leeks, celery.'),
                new Instructions('Add the jalapenos, a large handful of coriander and crumble the feta cheese into the mixture.'),
                new Instructions(  'Mix all the ingredients really well and season to taste.'),
                new Instructions( 'Put the bread crumbs in a plate,Shape the burger patties into with a cutter or mould.'),
                new Instructions('Dip the patty in the batter and cover with breadcrumbs,Heat up 2 tbsp oil in pan and shallow fry until nice and brown.'),
                new Instructions( 'Slice up some tomatoes and put it in a lettuce leaf for the garnish along with some gherkins.'),
                new Instructions( 'Heat the buns in the oven.'),
                new Instructions( 'Put the lettuce, tomatoes and gherkins inside the bun along with the patty and serve with chips on the side.')
                        ]),           
              new Recipe(
            10,
           'Veg Sandwich',
         'https://st.depositphotos.com/1010050/2506/i/950/depositphotos_25069951-stock-photo-vegetable-sandwiches.jpg',
            5.5,
            4,
            '15 min',
            '25 min',
            'sandwich',
            [
                new Ingredient( 'onions 2 tbsp'),
                new Ingredient('capscium 2 tbsp'  ),
                new Ingredient('boiled potato 2 tbsp'),
                new Ingredient('green chillies 2 tbsp'),
                new Ingredient('coriander leaves 1 tbsp'),
                new Ingredient('chaat masala ¼ tsp'),
                new Ingredient('black pepper powder	¼ tsp'),
                new Ingredient( 'mayonnaise	1 ½ tbsp' ),
                new Ingredient( 'bread	4 slices' ),
                new Ingredient( 'cheese slices	2'),
                new Ingredient( 'butter 1 tsp'),
                new Ingredient('Salt as per your taste' )
            ],
            [
                new Instructions('In a large mixing bowl add the onions, capsicum, tomatoes, green chillies, coriander leaves, boiled and mashed potato, salt, chaat masala and black pepper powder and mix well.'),
                new Instructions( 'Once mixed add the mayonnaise and mix the stuffing well.'),
                new Instructions('Take 2 slices of bread and generously apply the stuffing on both the slices of bread evenly.'),
                new Instructions('Place 1 cheese slice on top of one of the stuffing and land the other bread with the stuffing on, on top of the cheese slice.'),
                new Instructions( 'Now apply butter on the top side of the bread ,Land the buttered side bread on the pan and cook till it turns golden brown in colour.'),
                new Instructions('Then apply butter on the other slice of bread and cook this side as well till it turns golden in colour.'),
                new Instructions(   'Once both sides are grilled then remove them on a plate and cut diagonally and enjoy while it’s hot with some tomato ketchup or some spicy green chutney.'),
           
                  ]),        
              
                new Recipe(
            11,
           'Veg Cheese Sandwich',
        'https://img-global.cpcdn.com/recipes/f7da3dff291206ab/1200x630cq70/photo.jpg',
        4.4,
            2,
            '15 min',
            '25 min',
            'sandwich',
            [
                new Ingredient( 'onions 2 tbsp'),
                new Ingredient('capscium 2 tbsp'  ),
                new Ingredient('boiled potato 2 tbsp'),
                new Ingredient('green chillies 2 tbsp'),
                new Ingredient('coriander leaves 1 tbsp'),
                new Ingredient('chaat masala ¼ tsp'),
                new Ingredient('black pepper powder	¼ tsp'),
                new Ingredient( 'mayonnaise	1 ½ tbsp' ),
                new Ingredient( 'bread	4 slices' ),
                new Ingredient( 'cheese slices	2'),
                new Ingredient( 'butter 1 tsp'),
                new Ingredient('Salt as per your taste' )
            ],
            [
                new Instructions('In a large mixing bowl add the onions, capsicum, tomatoes, green chillies, coriander leaves, boiled and mashed potato, salt, chaat masala and black pepper powder and mix well.'),
                new Instructions( 'Once mixed add the mayonnaise and mix the stuffing well.'),
                new Instructions('Take 2 slices of bread and generously apply the stuffing on both the slices of bread evenly.'),
                new Instructions('Place 1 cheese slice on top of one of the stuffing and land the other bread with the stuffing on, on top of the cheese slice.'),
                new Instructions( 'Now apply butter on the top side of the bread ,Land the buttered side bread on the pan and cook till it turns golden brown in colour.'),
                new Instructions('Then apply butter on the other slice of bread and cook this side as well till it turns golden in colour.'),
                new Instructions(   'Once both sides are grilled then remove them on a plate and cut diagonally and enjoy while it’s hot with some tomato ketchup or some spicy green chutney.'),
           
                    ]),     
                new Recipe(
            12,
           'Paneer Sandwich',
       'https://img.freepik.com/premium-photo/paneer-bhurji-sandwich-is-tasty-paneer-based-dish-made-with-cottage-cheese-served-with-fresh-tomato-ketchup-green-mint-chutney-selective-focus_466689-30307.jpg',
        5.3,
            4,
            '15 min',
            '25 min',
            'sandwich',
            [
                new Ingredient( 'onions 2 tbsp'),
                new Ingredient('capscium 2 tbsp'  ),
                new Ingredient('paneer 2 cups'),
                new Ingredient('green chillies 2 tbsp'),
                new Ingredient('coriander leaves 1 tbsp'),
                new Ingredient('chaat masala ¼ tsp'),
                new Ingredient('black pepper powder	¼ tsp'),
                new Ingredient( 'mayonnaise	1 ½ tbsp' ),
                new Ingredient( 'bread	4 slices' ),
                new Ingredient( 'cheese slices	2'),
                new Ingredient( 'butter 1 tsp'),
                new Ingredient('Salt as per your taste' )
            ],
            [
                new Instructions('In a large mixing bowl add the onions, capsicum, tomatoes, green chillies, coriander leaves, boiled and mashed potato, salt, chaat masala and black pepper powder and mix well.'),
                new Instructions( 'Once mixed add the mayonnaise and mix the stuffing well.'),
                new Instructions('Take 2 slices of bread and generously apply the stuffing on both the slices of bread evenly.'),
                new Instructions('Place 1 cheese slice on top of one of the stuffing and land the other bread with the stuffing on, on top of the cheese slice.'),
                new Instructions( 'Now apply butter on the top side of the bread ,Land the buttered side bread on the pan and cook till it turns golden brown in colour.'),
                new Instructions('Then apply butter on the other slice of bread and cook this side as well till it turns golden in colour.'),
                new Instructions(   'Once both sides are grilled then remove them on a plate and cut diagonally and enjoy while it’s hot with some tomato ketchup or some spicy green chutney.'),
           
                    ]),   
                new Recipe(
            13,
           'Spinach & Corn Sandwich',
      'https://www.ruchikrandhap.com/wp-content/uploads/2017/09/Paneer-Corn-Spinach-Sandwich-4-1-1024x643.jpg',
        5.3,
            2,
            '20 min',
            '25 min',
            'sandwich',
                    [
                new Ingredient('chopped spinach 2 cups'),
                new Ingredient('boiled corn 1 cup'),
                new Ingredient( 'onions 2 tbsp'),
                new Ingredient('capscium 2 tbsp'  ),
                new Ingredient('paneer 2 cups'),
                new Ingredient('green chillies 2 tbsp'),
                new Ingredient('coriander leaves 1 tbsp'),
                new Ingredient('chaat masala ¼ tsp'),
                new Ingredient('black pepper powder	¼ tsp'),
                new Ingredient( 'mayonnaise	1 ½ tbsp' ),
                new Ingredient( 'bread	4 slices' ),
                new Ingredient( 'cheese slices	2'),
                new Ingredient( 'butter 1 tsp'),
                new Ingredient('Salt as per your taste' )
            ],
            [
                new Instructions('In a large mixing bowl add the onions, capsicum, tomatoes, green chillies, coriander leaves, boiled and mashed potato, salt, chaat masala and black pepper powder and mix well.'),
                new Instructions( 'Once mixed add the mayonnaise and mix the stuffing well.'),
                new Instructions('Take 2 slices of bread and generously apply the stuffing on both the slices of bread evenly.'),
                new Instructions('Place 1 cheese slice on top of one of the stuffing and land the other bread with the stuffing on, on top of the cheese slice.'),
                new Instructions( 'Now apply butter on the top side of the bread ,Land the buttered side bread on the pan and cook till it turns golden brown in colour.'),
                new Instructions('Then apply butter on the other slice of bread and cook this side as well till it turns golden in colour.'),
                new Instructions(   'Once both sides are grilled then remove them on a plate and cut diagonally and enjoy while it’s hot with some tomato ketchup or some spicy green chutney.'),
           
                    ]),   
                      new Recipe(
        14,
           'Egg Sandwich',
     'https://us.123rf.com/450wm/sonyakamoz/sonyakamoz1710/sonyakamoz171000238/88437886-healthy-breakfast-sandwiches-bread-toasts-with-fried-eggs-and-fresh-vegetables-on-wooden-board-over.jpg',
        5.3,
            2,
            '20 min',
            '25 min',
            'sandwich',
                    [
   
                new Ingredient('boiled eggs 2'),
                new Ingredient( 'onions 2 tbsp'),
                new Ingredient('capscium 2 tbsp'  ),
                new Ingredient('paneer 2 cups'),
                new Ingredient('green chillies 2 tbsp'),
                new Ingredient('coriander leaves 1 tbsp'),
                new Ingredient('chaat masala ¼ tsp'),
                new Ingredient('black pepper powder	¼ tsp'),
                new Ingredient( 'mayonnaise	1 ½ tbsp' ),
                new Ingredient( 'bread	4 slices' ),
                new Ingredient( 'cheese slices	2'),
                new Ingredient( 'butter 1 tsp'),
                new Ingredient('Salt as per your taste' )
            ],
            [
                new Instructions('In a large mixing bowl add the onions, capsicum, tomatoes, green chillies, coriander leaves, boiled and mashed potato, salt, chaat masala and black pepper powder and mix well.'),
                new Instructions( 'Once mixed add the mayonnaise and mix the stuffing well.'),
                new Instructions('Take 2 slices of bread and generously apply the stuffing on both the slices of bread evenly.'),
                new Instructions('Place 1 cheese slice on top of one of the stuffing and land the other bread with the stuffing on, on top of the cheese slice.'),
                new Instructions( 'Now apply butter on the top side of the bread ,Land the buttered side bread on the pan and cook till it turns golden brown in colour.'),
                new Instructions('Then apply butter on the other slice of bread and cook this side as well till it turns golden in colour.'),
                new Instructions(   'Once both sides are grilled then remove them on a plate and cut diagonally and enjoy while it’s hot with some tomato ketchup or some spicy green chutney.'),
           
                          ]), 
         new Recipe(
            15,
           'Black Forest Cake',
  'https://d33wubrfki0l68.cloudfront.net/cc8d307e0d502686770f2aec6fd0c57cd58982f3/1bfd0/images/uploads/2018_08_26_black_forest_cake_0.jpg',
        5.5,
            10,
            '60 min',
            '25 min',
            'cake',
                    [
   
                new Ingredient('2 cups white sugar'),
                new Ingredient( '¾ cup unsweetened cocoa powder'),
                new Ingredient( '1 ½ teaspoons baking powder'  ),
                new Ingredient( '¾ teaspoon baking soda'),
                new Ingredient( '¾ teaspoon salt'),
                new Ingredient('3 eggs'),
                new Ingredient('1 cup milk'),
                new Ingredient('½ cup vegetable oil'),
                new Ingredient(  '1 tablespoon vanilla extract' ),
        
            ],
            [
                new Instructions(  'Preheat the oven to 350 degrees F (175 degrees C). Grease and flour two 9-inch round cake pans; line bottoms with parchment paper. Place a medium bowl in the refrigerator to chill.'),
                new Instructions(  'Whisk flour, sugar, cocoa, baking powder, baking soda, and salt together in a large bowl. Add eggs, milk, oil, and vanilla; beat until combined. Pour cake batter into the prepared pans.'),
                new Instructions( 'Bake in the preheated oven until a toothpick inserted in the centers comes out clean, about 35 min. Cool layers in pans on wire racks for 10 min. Run a paring knife around edges to loosen and invert carefully onto racks to cool completely, 1 to 2 hours.'),
                new Instructions('While cake layers bake, drain cherries for topping, reserving 1/2 cup juice. Combine reserved juice, cherries, sugar, and cornstarch in a 2-quart saucepan. Cook, stirring constantly, over low heat until thickened. Stir in vanilla. Let cool at room temperature for 30 min. Transfer to the refrigerator to cool completely before assembling cake.'),
                new Instructions('Now apply butter on the top side of the bread ,Land the buttered side bread on the pan and cook till it turns golden brown in colour.'),
                new Instructions(    'Combine whipping cream and confectioners  sugar for frosting in the chilled medium bowl. Beat with an electric mixer at high speed until stiff peaks form..'),
                new Instructions('Split each cake layer in half horizontally using a long serrated knife. Tear one layer into crumbs; set aside. Gently brush loose crumbs off top and sides of remaining layers using a pastry brush or your hands. Reserve 1 1/2 cups frosting for piping decorations on cake; set aside.'),
           
             ]), 
         new Recipe(
            16,
           ' Red Velvet Cake',
 'https://img.freepik.com/premium-photo/red-velvet-cake-wooden-board_34439-725.jpg',
        5.5,
            12,
            '70 min',
            '35 min',
            'cake',
             [
                new Ingredient('red food color'),
                new Ingredient(' 2 ⅛ cups all-purpose flour'),
                new Ingredient('2 cups white sugar'),
                new Ingredient( '¾ cup unsweetened cocoa powder'),
                new Ingredient( '1 ½ teaspoons baking powder'  ),
                new Ingredient( '¾ teaspoon baking soda'),
                new Ingredient( '¾ teaspoon salt'),
                new Ingredient('3 eggs'),
                new Ingredient('1 cup milk'),
                new Ingredient('½ cup vegetable oil'),
                new Ingredient(  '1 tablespoon vanilla extract' ),
        
            ],
            [
                new Instructions(  'Preheat the oven to 350 degrees F (175 degrees C). Grease and flour two 9-inch round cake pans; line bottoms with parchment paper. Place a medium bowl in the refrigerator to chill.'),
                new Instructions(  'Whisk flour, sugar, cocoa, baking powder, baking soda, and salt together in a large bowl. Add eggs, milk, oil, and vanilla; beat until combined. Pour cake batter into the prepared pans.'),
                new Instructions( 'Bake in the preheated oven until a toothpick inserted in the centers comes out clean, about 35 min. Cool layers in pans on wire racks for 10 min. Run a paring knife around edges to loosen and invert carefully onto racks to cool completely, 1 to 2 hours.'),
                new Instructions('While cake layers bake, drain cherries for topping, reserving 1/2 cup juice. Combine reserved juice, cherries, sugar, and cornstarch in a 2-quart saucepan. Cook, stirring constantly, over low heat until thickened. Stir in vanilla. Let cool at room temperature for 30 min. Transfer to the refrigerator to cool completely before assembling cake.'),
                new Instructions('Now apply butter on the top side of the bread ,Land the buttered side bread on the pan and cook till it turns golden brown in colour.'),
                new Instructions(    'Combine whipping cream and confectioners  sugar for frosting in the chilled medium bowl. Beat with an electric mixer at high speed until stiff peaks form..'),
                new Instructions('Split each cake layer in half horizontally using a long serrated knife. Tear one layer into crumbs; set aside. Gently brush loose crumbs off top and sides of remaining layers using a pastry brush or your hands. Reserve 1 1/2 cups frosting for piping decorations on cake; set aside.'),
           
                          ]), 
                       new Recipe(
        17,
           'Coffee Cake',
 'https://thecafesucrefarine.com/wp-content/uploads/2016/11/Easy-Overnight-Coffee-Cake-4.jpg',
        5.5,
            10,
            '50 min',
            '30 min',
            'cake',
             [
           
                new Ingredient(' 2 ⅛ cups all-purpose flour'),
                new Ingredient('2 cups white sugar'),
                new Ingredient( '¾ cup unsweetened cocoa powder'),
                new Ingredient( '1 ½ teaspoons baking powder'  ),
                new Ingredient( '¾ teaspoon baking soda'),
                new Ingredient( '¾ teaspoon salt'),
                new Ingredient('3 eggs'),
                new Ingredient('1 cup milk'),
                new Ingredient('½ cup vegetable oil'),
                new Ingredient(  '1 tablespoon vanilla extract' ),
        
            ],
            [
                new Instructions(  'Preheat the oven to 350 degrees F (175 degrees C). Grease and flour two 9-inch round cake pans; line bottoms with parchment paper. Place a medium bowl in the refrigerator to chill.'),
                new Instructions(  'Whisk flour, sugar, cocoa, baking powder, baking soda, and salt together in a large bowl. Add eggs, milk, oil, and vanilla; beat until combined. Pour cake batter into the prepared pans.'),
                new Instructions( 'Bake in the preheated oven until a toothpick inserted in the centers comes out clean, about 35 min. Cool layers in pans on wire racks for 10 min. Run a paring knife around edges to loosen and invert carefully onto racks to cool completely, 1 to 2 hours.'),
                new Instructions('While cake layers bake, drain cherries for topping, reserving 1/2 cup juice. Combine reserved juice, cherries, sugar, and cornstarch in a 2-quart saucepan. Cook, stirring constantly, over low heat until thickened. Stir in vanilla. Let cool at room temperature for 30 min. Transfer to the refrigerator to cool completely before assembling cake.'),
                new Instructions('Now apply butter on the top side of the bread ,Land the buttered side bread on the pan and cook till it turns golden brown in colour.'),
                new Instructions(    'Combine whipping cream and confectioners  sugar for frosting in the chilled medium bowl. Beat with an electric mixer at high speed until stiff peaks form..'),
                new Instructions('Split each cake layer in half horizontally using a long serrated knife. Tear one layer into crumbs; set aside. Gently brush loose crumbs off top and sides of remaining layers using a pastry brush or your hands. Reserve 1 1/2 cups frosting for piping decorations on cake; set aside.'),
           
                           ]), 
        new Recipe(
            18,
           'Mango Cup Cake',
'https://i.pinimg.com/564x/59/96/fa/5996fa7262f20043fedbf482fbda5f72.jpg',
        5.2,
            12,
            '55 min',
            '35nmin',
            'cake',
             [
                new Ingredient('mango pupl and pieces 2 cup'),
                new Ingredient(' 2 ⅛ cups all-purpose flour'),
                new Ingredient('2 cups white sugar'),
                new Ingredient( '¾ cup unsweetened cocoa powder'),
                new Ingredient( '1 ½ teaspoons baking powder'  ),
                new Ingredient( '¾ teaspoon baking soda'),
                new Ingredient( '¾ teaspoon salt'),
                new Ingredient('3 eggs'),
                new Ingredient('1 cup milk'),
                new Ingredient('½ cup vegetable oil'),
                new Ingredient(  '1 tablespoon vanilla extract' ),
        
            ],
            [
                new Instructions(  'Preheat the oven to 350 degrees F (175 degrees C). Grease and flour two 9-inch round cake pans; line bottoms with parchment paper. Place a medium bowl in the refrigerator to chill.'),
                new Instructions(  'Whisk flour, sugar, cocoa, baking powder, baking soda, and salt together in a large bowl. Add eggs, milk, oil, and vanilla; beat until combined. Pour cake batter into the prepared pans.'),
                new Instructions( 'Bake in the preheated oven until a toothpick inserted in the centers comes out clean, about 35 min. Cool layers in pans on wire racks for 10 min. Run a paring knife around edges to loosen and invert carefully onto racks to cool completely, 1 to 2 hours.'),
                new Instructions('While cake layers bake, drain cherries for topping, reserving 1/2 cup juice. Combine reserved juice, cherries, sugar, and cornstarch in a 2-quart saucepan. Cook, stirring constantly, over low heat until thickened. Stir in vanilla. Let cool at room temperature for 30 min. Transfer to the refrigerator to cool completely before assembling cake.'),
                new Instructions('Now apply butter on the top side of the bread ,Land the buttered side bread on the pan and cook till it turns golden brown in colour.'),
                new Instructions(    'Combine whipping cream and confectioners  sugar for frosting in the chilled medium bowl. Beat with an electric mixer at high speed until stiff peaks form..'),
                new Instructions('Split each cake layer in half horizontally using a long serrated knife. Tear one layer into crumbs; set aside. Gently brush loose crumbs off top and sides of remaining layers using a pastry brush or your hands. Reserve 1 1/2 cups frosting for piping decorations on cake; set aside.'),
           
            ]),    
          
        new Recipe(
            19,
           'Choco Cup Cake',
'https://st2.depositphotos.com/1773130/7992/i/450/depositphotos_79925368-stock-photo-chocolate-cupcakes-with-a-cup.jpg',
        5.2,
            12,
            '55 min',
            '35nmin',
            'cake',
             [
                
                new Ingredient(' 2 ⅛ cups all-purpose flour'),
                new Ingredient('2 cups white sugar'),
                new Ingredient( '¾ cup unsweetened cocoa powder'),
                new Ingredient( '1 ½ teaspoons baking powder'  ),
                new Ingredient( '¾ teaspoon baking soda'),
                new Ingredient( '¾ teaspoon salt'),
                new Ingredient('3 eggs'),
                new Ingredient('1 cup milk'),
                new Ingredient('½ cup vegetable oil'),
                new Ingredient(  '1 tablespoon vanilla extract' ),
        
            ],
            [
                new Instructions(  'Preheat the oven to 350 degrees F (175 degrees C). Grease and flour two 9-inch round cake pans; line bottoms with parchment paper. Place a medium bowl in the refrigerator to chill.'),
                new Instructions(  'Whisk flour, sugar, cocoa, baking powder, baking soda, and salt together in a large bowl. Add eggs, milk, oil, and vanilla; beat until combined. Pour cake batter into the prepared pans.'),
                new Instructions( 'Bake in the preheated oven until a toothpick inserted in the centers comes out clean, about 35 min. Cool layers in pans on wire racks for 10 min. Run a paring knife around edges to loosen and invert carefully onto racks to cool completely, 1 to 2 hours.'),
                new Instructions('While cake layers bake, drain cherries for topping, reserving 1/2 cup juice. Combine reserved juice, cherries, sugar, and cornstarch in a 2-quart saucepan. Cook, stirring constantly, over low heat until thickened. Stir in vanilla. Let cool at room temperature for 30 min. Transfer to the refrigerator to cool completely before assembling cake.'),
                new Instructions('Now apply butter on the top side of the bread ,Land the buttered side bread on the pan and cook till it turns golden brown in colour.'),
                new Instructions(    'Combine whipping cream and confectioners  sugar for frosting in the chilled medium bowl. Beat with an electric mixer at high speed until stiff peaks form..'),
                new Instructions('Split each cake layer in half horizontally using a long serrated knife. Tear one layer into crumbs; set aside. Gently brush loose crumbs off top and sides of remaining layers using a pastry brush or your hands. Reserve 1 1/2 cups frosting for piping decorations on cake; set aside.'),
           
            ]),   
         new Recipe(
            20,
           'Mango Icecream',
'https://img.freepik.com/premium-photo/homemade-mango-ice-cream-bowls-with-fresh-fruits-dark-gray_186277-2005.jpg',
        5.2,
            12,
            '170 min',
            '35 min',
            'icecream',
             [
                
                new Ingredient(  '2 tbsp vanila extract'),
                new Ingredient( '2 + ¼ cup milk'),
                new Ingredient( '½ cup sugar'),
                new Ingredient( '8-10 saffron strands' ),
                new Ingredient(  'or ½ cup store bought condensed milk'),
                new Ingredient(  '1 cup mango puree'),
                new Ingredient(  '1 cup whipping cream'),
                new Ingredient('1 cup milk'),
                new Ingredient( '½ cup fresh mango chunks'),
               
        
            ],
            [
                new Instructions('In a non-stick saucepan, set over a medium heat; add milk and sugar. Give it a mix and let it come to a simmer..', ),
                new Instructions(  'Add saffron strands and give it a mix.', ),
                new Instructions( 'Keep stirring the mixture till it thickens and reduces to ⅓ of its original quantity. Take it off the heat but keep stirring for another 2 min. Let it cool and transfer it into a bowl.',),
                new Instructions( ' Add mango puree to it and give it a good mix. Keep it aside.',),
                new Instructions( 'You can also use ½ cup store bought condensed milk instead of the one we made.',),
                new Instructions('In another bowl, whip the whipping cream till soft peaks.',   ),
                new Instructions( 'Fold the whipped cream with the mango mixture and mix them gently.'),
                new Instructions( 'Fold the mango chunks into it and pour the mixture into a container or a loaf pan like me.'  ),
                new Instructions( 'Cling wrap the container properly and freeze it for 6-8 hours; dig in and enjoy!.')
             ]),   
         new Recipe(
            21,
           'Choco Icecream',
'https://previews.123rf.com/images/tobi/tobi1412/tobi141200033/34439224-scoops-of-dark-chocolate-ice-cream.jpg',
        5.2,
            12,
            '170 min',
            '35 min',
            'icecream',
             [
                new Ingredient('1cup choco chips'),
                new Ingredient(  '2 tbsp vanila extract'),
                new Ingredient( '2 + ¼ cup milk'),
                new Ingredient( '½ cup sugar'),
                new Ingredient( '8-10 saffron strands' ),
                new Ingredient(  'or ½ cup store bought condensed milk'),
                new Ingredient(  '1 cup mango puree'),
                new Ingredient(  '1 cup whipping cream'),
                new Ingredient('1 cup milk'),
                new Ingredient( '½ cup coco powder'),
               
        
            ],
            [
                new Instructions('In a non-stick saucepan, set over a medium heat; add milk and sugar. Give it a mix and let it come to a simmer..', ),
                new Instructions(  'Add saffron strands and give it a mix.', ),
                new Instructions( 'Keep stirring the mixture till it thickens and reduces to ⅓ of its original quantity. Take it off the heat but keep stirring for another 2 min. Let it cool and transfer it into a bowl.',),
                new Instructions( ' Add mango puree to it and give it a good mix. Keep it aside.',),
                new Instructions( 'You can also use ½ cup store bought condensed milk instead of the one we made.',),
                new Instructions('In another bowl, whip the whipping cream till soft peaks.',   ),
                new Instructions( 'Fold the whipped cream with the mango mixture and mix them gently.'),
                new Instructions( 'Fold the mango chunks into it and pour the mixture into a container or a loaf pan like me.'  ),
                new Instructions( 'Cling wrap the container properly and freeze it for 6-8 hours; dig in and enjoy!.')
             ]),   
             new Recipe(
            22,
           'Coffee Icecream',
'https://st3.depositphotos.com/1027198/14795/i/600/depositphotos_147957555-stock-photo-coffee-ice-cream.jpg',
        5.2,
            12,
            '170 min',
            '35 min',
            'icecream',
             [
                new Ingredient('1cup choco chips'),
                new Ingredient(  '2 tbsp vanila extract'),
                new Ingredient( '2 + ¼ cup milk'),
                new Ingredient( '½ cup sugar'),
                new Ingredient( '8-10 saffron strands' ),
                new Ingredient(  'or ½ cup store bought condensed milk'),
                new Ingredient(  '1 cup mango puree'),
                new Ingredient(  '1 cup whipping cream'),
                new Ingredient('1 cup milk'),
                new Ingredient( '½ cup coco powder'),
               
        
            ],
            [
                new Instructions('In a non-stick saucepan, set over a medium heat; add milk and sugar. Give it a mix and let it come to a simmer..', ),
                new Instructions(  'Add saffron strands and give it a mix.', ),
                new Instructions( 'Keep stirring the mixture till it thickens and reduces to ⅓ of its original quantity. Take it off the heat but keep stirring for another 2 min. Let it cool and transfer it into a bowl.',),
                new Instructions( ' Add mango puree to it and give it a good mix. Keep it aside.',),
                new Instructions( 'You can also use ½ cup store bought condensed milk instead of the one we made.',),
                new Instructions('In another bowl, whip the whipping cream till soft peaks.',   ),
                new Instructions( 'Fold the whipped cream with the mango mixture and mix them gently.'),
                new Instructions( 'Fold the mango chunks into it and pour the mixture into a container or a loaf pan like me.'  ),
                new Instructions( 'Cling wrap the container properly and freeze it for 6-8 hours; dig in and enjoy!.')
                 ]),  
              new Recipe(
            23,
          'Rose & Tender Coconut Icecream',
'https://blog.cruisefashion.com/image.axd?picture=/cocorose2.jpg',
        5.2,
            12,
            '170 min',
            '35 min',
            'icecream',
             [
                new Ingredient('1cup choco chips'),
                new Ingredient(  '2 tbsp vanila extract'),
                new Ingredient( '2 + ¼ cup milk'),
                new Ingredient( '½ cup sugar'),
                new Ingredient( '8-10 saffron strands' ),
                new Ingredient(  'or ½ cup store bought condensed milk'),
                new Ingredient(  '1 cup mango puree'),
                new Ingredient(  '1 cup whipping cream'),
                new Ingredient('1 cup milk'),
                new Ingredient( '½ cup coco powder'),
               
        
            ],
            [
                new Instructions('In a non-stick saucepan, set over a medium heat; add milk and sugar. Give it a mix and let it come to a simmer..', ),
                new Instructions(  'Add saffron strands and give it a mix.', ),
                new Instructions( 'Keep stirring the mixture till it thickens and reduces to ⅓ of its original quantity. Take it off the heat but keep stirring for another 2 min. Let it cool and transfer it into a bowl.',),
                new Instructions( ' Add mango puree to it and give it a good mix. Keep it aside.',),
                new Instructions( 'You can also use ½ cup store bought condensed milk instead of the one we made.',),
                new Instructions('In another bowl, whip the whipping cream till soft peaks.',   ),
                new Instructions( 'Fold the whipped cream with the mango mixture and mix them gently.'),
                new Instructions( 'Fold the mango chunks into it and pour the mixture into a container or a loaf pan like me.'  ),
                new Instructions( 'Cling wrap the container properly and freeze it for 6-8 hours; dig in and enjoy!.')
                          ]),  
    ]

    getRecipes() {
        return this.recipes.slice();
    }
    getRecipe(index:number) {
        return this.recipes[index];
    }
}